name: Rebuild stromstotte site

# Controls when the action will run. (making sure it is run after stromstotte is ran)
# 13.20, 13.30, 13.50
on:
  schedule:
    - cron:  '20,30,50 12 * * *'
  push:


jobs:
  touch-and-rebuild:
    runs-on: ubuntu-20.04 #ubuntu-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::here
          any::blogdown
    - name: Install Hugo
      run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.87.0")'
    - name: Build site
      run: |
        blogdown:::touch_file(here::here("content", "sideprojects","stromstotte", "index.Rmd"))
        blogdown:::build_site(run_hugo=FALSE, build_rmd = "content/sideprojects/stromstotte/index.Rmd")
      shell: Rscript {0}


# Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add *
        git commit -am "GHA rebuild stromstotte $(date)"
        git push
